name: "Hello world docker github action"
description: "Greet someone and record the time"
inputs:
  who-to-greet: # id of the imput
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  time: # id of the output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args: 
    - ${{ inputs.who-to-greet }}